# Generated by Django 2.2 on 2022-06-17 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_student_dashboard_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dashboard_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='dashboard_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.StudentDashboardUser'),
        ),
    ]
